consol.log('Hello programer')
consol.log('I love Bangladesh')
consol.log('Bangladesh is a small country')
consol.log('3'+3)
consol.log(3+3)
consol.log('My fv no:'+3)
consol.log('string+string')
consol.log('string+ 3')